# Generated by Django 4.2 on 2023-04-19 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_marks_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
